FROM node:6.10.3

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
ONBUILD VOLUME ["/usr/src/app"]


ONBUILD ARG NODE_ENV
ONBUILD ENV NODE_ENV $NODE_ENV
ONBUILD COPY package.json /usr/src/app/
# ONBUILD RUN npm install && npm cache clean
# ONBUILD RUN npm install mocha -g 

RUN npm install && npm cache clean
RUN npm install mocha -g 
CMD [ "npm", "test" ]
# CMD ["bash"]
